spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dreamsapp-goals?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8083